name: Update Dependencies

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
    - name: Update dependencies
      run: |
        # Update all dependencies to latest compatible versions
        npx npm-check-updates -u
        npm install
        
    - name: Run tests
      run: |
        npm run lint
        npm run build
        npm test
        
    - name: Check for changes
      id: changes
      run: |
        if git diff --quiet; then
          echo "HAS_CHANGES=false" >> $GITHUB_OUTPUT
        else
          echo "HAS_CHANGES=true" >> $GITHUB_OUTPUT
        fi
        
    - name: Create Pull Request
      if: steps.changes.outputs.HAS_CHANGES == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: update dependencies"
        title: "🔄 Automated dependency updates"
        body: |
          ## 📦 Dependency Updates
          
          This PR contains automated dependency updates:
          
          - Updated all dependencies to their latest compatible versions
          - All tests are passing ✅
          - Ready for review and merge
          
          ### Changes
          - Updated package-lock.json with new dependency versions
          - No breaking changes detected
          
          ---
          🤖 This PR was created automatically by GitHub Actions
        branch: "automated-dependency-updates"
        delete-branch: true